let shopItemsData = [
    {
        id: "unique1",
        name: "Casual Shirt",
        price: 45,
        desc: "Comfortable and stylish everyday wear.",
        img: "images/img-1.jpg",
    },
    {
        id: "unique2",
        name: "Office Shirt",
        price: 100,
        desc: "Perfect for a professional look.",
        img: "images/img-2.jpg",
    },
    {
        id: "unique3",
        name: "T Shirt",
        price: 25,
        desc: "Lightweight and casual for daily use.",
        img: "images/img-3.jpg",
    },
    {
        id: "unique4",
        name: "Mens Suit",
        price: 300,
        desc: "Elegant suit for formal occasions.",
        img: "images/img-4.jpg",
    },
    {
        id: "unique5",
        name: "Mens Tie",
        price: 25,
        desc: "Classic tie to complete your outfit.",
        img: "images/img-5.png",
    },
    {
        id: "unique6",
        name: "Casual Shoes",
        price: 200,
        desc: "Trendy shoes for relaxed outings.",
        img: "images/img-6.png",
    },
    {
        id: "unique7",
        name: "Black Suit",
        price: 450,
        desc: "Timeless black suit for any event.",
        img: "images/img-7.png",
    },
    {
        id: "unique8",
        name: "Polo Shirt",
        price: 45,
        desc: "Classic polo for a smart-casual look.",
        img: "images/img-8.png",
    },
    {
        id: "unique9",
        name: "Denim Shirt",
        price: 85,
        desc: "Stylish denim for a rugged look.",
        img: "images/img-9.png",
    },
    {
        id: "unique10",
        name: "Denim Pants",
        price: 120,
        desc: "Durable and versatile denim pants.",
        img: "images/img-10.png",
    },
    {
        id: "unique11",
        name: "Basic Cap",
        price: 35,
        desc: "Casual cap for sun protection.",
        img: "images/img-11.png",
    },
    {
        id: "unique12",
        name: "Leather Boots",
        price: 350,
        desc: "Premium boots for a rugged style.",
        img: "images/img-12.png",
    }
];
